GET http://localhost:3001/api/blogs

###
POST http://localhost:3001/api/blogs/ HTTP/1.1
content-type: application/json

{
    "title": "You don't know JS",
    "author": "Kyle Simpson",
    "url": "https://github.com/getify/You-Dont-Know-JS",
    "likes": 3
}

###
POST http://localhost:3001/api/users/ HTTP/1.1
content-type: application/json

{
    "username": "Relativity",
    "name": "Albert Enstein",
    "password": "password"
}