GET http://localhost:3001/api/blogs

###
POST http://localhost:3001/api/blogs/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkVtcGVyb3IiLCJpZCI6IjY1MTg3N2JlMWU1M2Q2MGU5NzYwZDE4ZSIsImlhdCI6MTY5NjI4MDQ3OSwiZXhwIjoxNjk2Mjg0MDc5fQ.VbrIOeVxqo3A1POgcYRje3IM4Fb1vfQJblVKysz7kas

{
    "title": "Why do you control?",
    "author": "Marcus Aurelius",
    "url": "https://github.com/getify/You-Dont-Know-JS",
    "likes": 4
}

###
POST http://localhost:3001/api/users/ HTTP/1.1
content-type: application/json

{
    "username": "Relativity",
    "name": "Albert Enstein",
    "password": "password"
}

###
DELETE http://localhost:3001/api/blogs/651b142a961acc69a4989e2d HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkVtcGVyb3IiLCJpZCI6IjY1MTg3N2JlMWU1M2Q2MGU5NzYwZDE4ZSIsImlhdCI6MTY5NjI3MzU1MiwiZXhwIjoxNjk2Mjc3MTUyfQ.D7T1zjnoPE7MgAA0wJhOC-ygk2s33n2DKl92ZgkOMoM
